# Generated by Django 4.1.3 on 2022-12-03 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="MenuitemsID",
        ),
    ]
