# Generated by Django 4.1.4 on 2022-12-31 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittlelemonAPI", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Categories",
        ),
        migrations.RenameModel(
            old_name="MenuItem",
            new_name="MenuItems",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
