# Generated by Django 4.1.4 on 2022-12-31 13:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "LittlelemonAPI",
            "0002_rename_category_categories_rename_menuitem_menuitems_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Order",
            new_name="Orders",
        ),
    ]
